#!/bin/bash
#    bl-install: a wrapper round the promptInstall() function in bl-includes
#    It may be called by other scripts or menus
#    to install Debian packages in a popup terminal window.
#    ( It is not needed in a script known to be running in a terminal;
#     in that case, just use promptInstall() )
#
#    Copyright (C) 2016-2019 John Crawley    <john@bunsenlabs.org>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

HELP='bl-install: a wrapper round the promptInstall() function in bl-includes

Usage:
bl-install -n "name of app(s)" -m "message text" -f "/path/to/file" [apt option] package [package...]

    -h --help                   show this message and exit
    -n --name       <string>    descriptive name of package(s) to be installed
    -m --message    <string>    message to display to user before installing
    -f --file       <filepath>  file to hold return value of script on exit

Specified options may be provided in any order.
If -n, -m or -f are used, they must be followed by an argument.
If -n or -m are absent they will be generated automatically.
If -f is set, the script will write its exit return value there,
so a calling script can test for success.
All other arguments are taken as apt-get options or package names to install.

This script will open a new terminal window to run the installer,
and fetch the return value from a temporary file.
This is useful if launching from a GUI, but in a script known to be
already running in a terminal, it is not needed.
The promptInstall() function from bl-includes is enough.
'

BL_COMMON_LIBDIR='/usr/lib/bunsen/common'

trap 'send_return' EXIT

send_return(){
    local retval=$?
    [[ -n "$retfile" ]] && echo "$retval" > "$retfile"
}

if ! . "$BL_COMMON_LIBDIR/bl-includes" 2> /dev/null; then
    echo $"Error: Failed to locate bl-includes in $BL_COMMON_LIBDIR" >&2
    exit 1
fi

name=
message=
retfile=
args=()
packages=()

while [[ ${1+x} ]]
do
    case "$1" in
    -n|--name)
        name="$2"
        shift 2
        ;;
    -m|--message)
        message="$2"
        shift 2
        ;;
    -f|--file)
        retfile="$2"
        shift 2
        ;;
    -h|--help)
        echo "$HELP"
        exit 0
        ;;
    -t|--target-release|--default-release|-c|--config-file|-o|--option) # apt-get options taking a value
        args+=( "$1" "$2" )
        shift 2
        ;;
    -*) # other apt-get options
        args+=($1)
        shift
        ;;
    *)
        args+=($1)
        packages+=($1) # assume any other argument is a package
        shift
        ;;
    esac
done

[[ ${#packages[@]} -gt 0 ]] || {
    echo "$0: no packages specified"$'\n' >&2
    echo "$HELP"
    exit 1
}

[[ $name ]] || {
    words=(${packages[0]//-/ })
    name="${words[*]^}"
}

[[ $message ]] || {
    message="This script will install $name"
}

if [[ -n "$retfile" ]]
then
    terminalCheck -T "Install $name" --file "$retfile" --name "$name" --message "$message" "${args[@]}"
else
    terminalCheck -T "Install $name" --name "$name" --message "$message" "${args[@]}"
fi

for i in "${packages[@]}"
do
    [[ $i =~ ^[a-z0-9][a-z0-9+.-]+$ ]] || {
        say "$i is not a valid Debian package name"$'\n' >&2
        echo "$HELP"
        exit 1
    }
done

allInstalled "${packages[@]}" && {
    say "$name: already installed"
    sleep 2
    exit 0
}

promptInstall "$name" "$message" "${args[@]}" || errorExit 'Install failed or abandoned.'

exit
